### ISSUE TITLE
Application type

### ISSUE THREAD

**Issue by KrunchMuffin** [GiancarloGomez/sentry-cfml#2]
FYI. The docs refer to `useSignature` but it does not exist.

I assume we should select Java for application type in Sentry?
I can't seem to get it to report, if that is correct. Not sure if it even matters.
I know it's not failing because my BugLog will run right after it and I get that report. I tried with and w/o threading.

Any ideas?

**Comment by KrunchMuffin** [comment]
I just checked the cf logs and and saw a 400 for the post, so I dumped the http result and got this

> X-Sentry-Error: Bad data reconstructing object (JSONDecodeError, Expecting value: line 1 column 6765 (char 6764))

It's sending malformed JSON. I don't want to post the JSON here, but I can send if you want to look.

**Comment by KrunchMuffin** [comment]
Sorry for all the posts. SO I replaced your json method with ben nadels version and it appears to work, however, has the API changed?

> sentry.interfaces.user: Discarded unknown attribute
    sentry.interfaces.exception: Discarded unknown attribute
    sentry.interfaces.http: Discarded unknown attribute
    sentry.interfaces.stacktrace: Discarded unknown attribute

**Comment by GiancarloGomez** [comment]
Hi, sorry for the errors you have been getting. My apps currently using this with Sentry aren't experiencing any issues. If I remember correctly, I just set up a project and get my DSN and then just go. I skip the selection of language.

**Comment by GiancarloGomez** [comment]
The jsonEncode is from the original project https://github.com/jmacul2/raven-cfml. If you want to share with me that is fine but I am not getting any errors. What are you passing to it that causes it to break?

**Comment by KrunchMuffin** [comment]
If I try to use the DSN, I get a parse error. The new DSN's are different than the legacy ones. So I put in all 3 values of keys and project id instead.
![image](https://user-images.githubusercontent.com/1037197/49666733-f8858000-fa26-11e8-91a3-cea4048b24cc.png)

**Comment by KrunchMuffin** [comment]
As far as what I am sending, it would break on E164 phone number because of the + and it was trying to send it as a number instead of a string. Same with just  a dial code of +1

**Comment by GiancarloGomez** [comment]
Yes I do not use the legacy DSN either. Where are you passing that data? In the exception? As an additional item?

**Comment by KrunchMuffin** [comment]
no, in the init

    application.sentry = new com.sentry(
        release: "1542414252",
        environment: "#request.environment#",
        publicKey   : "059xxxxxxxxxxxxxxxxxxxxxxxxxxx20b6b",
        privateKey  : "cab4xxxxxxxxxxxxxxxxxxxxxxxxxxx6f84cd",
        projectID   : "13xxxxxxxxxx"
    );

**Comment by KrunchMuffin** [comment]
hmmm..unless u have a different version than the one here, the parseDSN() is looking for the OLD DSN
`^(?:(\w+):)?\/\/(\w+):(\w+)?@([\w\.-]+)\/(.*)`

**Comment by GiancarloGomez** [comment]
I was talking about the phone number that causes the error. If you see my docs I do not show using the full DSN instead each key as you have. Although it is in the init, I don't use it so I have not tested in a while.

**Comment by KrunchMuffin** [comment]
sorry, misread. The data was getting passed in the hardcoded `form` here
https://github.com/GiancarloGomez/sentry-cfml/blob/7e044070dbbe03b771f6dcf50e50b74203eaa3af/sentry.cfc#L357

I have it working now, but I had to rewrite a portion of it. Not sure how/why it's still working for you.
But most of the lines with "interfaces" ie. `sentry.interfaces.exception` looks like they have removed the `sentry.interfaces` and changed to just `exception`.
https://docs.sentry.io/development/sdk-dev/interfaces/exception/
`sentry.interfaces.Http` is actually just `request`
https://docs.sentry.io/development/sdk-dev/interfaces/http/

I will probably fork and do a new version if I have time.

Thanks for the help!
